# SonarQube Project Details
sonar.projectKey=devsecops-demo
sonar.projectName=DevSecOps Demo
sonar.projectVersion=1.0

# Source Code
sonar.sources=src/main/java
sonar.tests=src/test/java

# Java Binaries
sonar.java.binaries=target/classes

# JaCoCo Coverage Report
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Encoding
sonar.sourceEncoding=UTF-8